#!/usr/bin/env python3
# =============================================================================
# PRIMITIVES T8(b) -- the adjoint class of the arrival operation and the signature of Gamma_4.   (Will, 2026-09-04)
#
#   Will: Gamma_4 is a TWISTED intertwiner, Gamma_4 rho_+(x) = rho_-(alpha(x)) Gamma_4 with alpha the grade involution
#   (exact).  With Gamma_4 = [[0, a Gamma_C],[b Gamma_C, 0]] and Gamma_C^T = -Gamma_C:  Gamma_4^T = Gamma_4 iff b = -a
#   iff Gamma_4^2 = +a^2 (self-adjoint observable -> Cl(3,1));  Gamma_4^T = -Gamma_4 iff b = a iff Gamma_4^2 = -a^2
#   (skew-adjoint generator -> Cl(2,2)).  CAUTION: the transpose must be replaced by the adjoint induced by the seat's
#   actual spinor bilinear B, Gamma^dag = B^{-1} Gamma^T B, and B must be DERIVED from the readout, not chosen for 3+1.
#   Boundaries: the algebra gives two chiral sectors ('particle and shadow' is interpretation); measuring Gamma_4
#   selects superpositions of the I = +-1 blocks, not the blocks, since {I, Gamma_4} = 0.
# CHECKS:
#   b1  twisted-intertwiner relation, exact.
#   b2  plain transpose: symmetric <-> square +a^2; antisymmetric <-> square -a^2.
#   b3  the seat's per-block spinor bilinear: solve for B_2 invariant under the spin group of the seat's form
#       (generated by the three bivectors).  Result: unique up to scale, ANTISYMMETRIC (symplectic), B_2 = Gamma_C.
#   b4  on the 4-dim space the Cl(2,1)-invariant bilinear is B_4 = diag(b+ Gamma_C, b- Gamma_C): two scales, one
#       relative sign s = sgn(b+ b-).  Under the induced adjoint, Gamma_4 self-adjoint  <=>  Gamma_4^2 = s a^2.
#       THE SIGNATURE OF THE FOURTH DIRECTION IS THE RELATIVE SIGN OF THE SPINOR BILINEAR ACROSS THE SHEETS.
#   b5  does requiring B_4 to be Gamma_4-invariant (up to sign) fix s?  Computed.
#   b6  the measurement boundary: Gamma_4's eigenvectors have both block components nonzero; I and Gamma_4 have no
#       joint eigenvector; a definite block needs an I-measurement.
# =============================================================================
import sympy as sp, itertools, time
T0 = time.time(); CH = []
def check(t, ok, n=""):
    CH.append(bool(ok))
    print(f"  [{'PASS' if ok else 'FAIL'}][{time.time()-T0:5.1f}s] {t}" + (f" -- {n}" if n else ""), flush=True)
def zM(M): return all(sp.simplify(e) == 0 for e in M)

g_H = sp.Matrix([[0, 1], [1, 0]]); g_G = sp.Matrix([[1, 0], [0, -1]]); g_C = sp.Matrix([[0, 1], [-1, 0]])
Z = sp.zeros(2)
blk = lambda A, B: sp.Matrix(sp.BlockMatrix([[A, Z], [Z, B]]))
off = lambda A, B: sp.Matrix(sp.BlockMatrix([[Z, A], [B, Z]]))
G_C = blk(g_C, -g_C); G_H = blk(g_H, g_H); G_G = blk(g_G, g_G); I4 = G_C*G_H*G_G
gens = {'C': G_C, 'H': G_H, 'G': G_G}
rho_p = {'C': g_C, 'H': g_H, 'G': g_G}; rho_m = {'C': -g_C, 'H': g_H, 'G': g_G}
a, b = sp.symbols('a b', real=True)
G4 = off(a*g_C, b*g_C)

print("=== b1: twisted intertwiner ===")
alpha_inv = lambda x: -x          # grade involution on generators
# upper block of Gamma_4 is A = a g_C: A rho_+(x) = rho_-(alpha(x)) A ?
A = a*g_C
check("b1 Gamma_4 rho_+(x) = rho_-(alpha(x)) Gamma_4 on every generator, alpha the grade involution: a TWISTED intertwiner, exact",
      all(zM(A*rho_p[k] - rho_m[k]*(-1)*A) for k in 'CHG'))

print("=== b2: plain transpose ===")
check("b2 Gamma_C^T = -Gamma_C; Gamma_4^T = Gamma_4 iff b = -a iff Gamma_4^2 = +a^2;  Gamma_4^T = -Gamma_4 iff b = a iff Gamma_4^2 = -a^2",
      g_C.T == -g_C and zM((G4.T - G4).subs(b, -a)) and zM((G4**2 - a**2*sp.eye(4)).subs(b, -a))
      and zM((G4.T + G4).subs(b, a)) and zM((G4**2 + a**2*sp.eye(4)).subs(b, a)))

print("=== b3: the seat's per-block spinor bilinear, DERIVED ===")
# the spin group of the seat's (2,1) form in the 2-dim rep is generated by the bivectors; a bilinear B_2 is invariant
# iff X^T B_2 + B_2 X = 0 for every bivector X
bivs = [g_H*g_G, g_C*g_H, g_C*g_G]
B2 = sp.Matrix(2, 2, sp.symbols('B0:4', real=True))
sol = sp.solve([e for X in bivs for e in list(X.T*B2 + B2*X)], list(B2), dict=True)
B2s = B2.subs(sol[0]); free2 = sorted(B2s.free_symbols, key=str)
check("b3 the spin-invariant bilinear on a block is UNIQUE up to scale", len(free2) == 1)
scale = free2[0]
check("b3' it is ANTISYMMETRIC -- symplectic -- and proportional to Gamma_C itself: B_2 = k Gamma_C.  The seat's spinor form is not the positive one; it is the timelike generator",
      zM(B2s + B2s.T) and zM(B2s - scale*g_C/(g_C[0,1]) * (B2s[0,1]/scale)) and zM(B2s - B2s[0,1]*g_C))
# adjoints of the generators under B_2: which are self-adjoint, which skew?
adj2 = lambda X: B2s.inv()*X.T*B2s
adj_signs = {k: ('self' if zM(adj2(rho_p[k]) - rho_p[k]) else 'skew' if zM(adj2(rho_p[k]) + rho_p[k]) else 'neither') for k in 'CHG'}
check("b3'' under the seat's bilinear every generator is SKEW-adjoint (X^dag = -X): the vectors act as anti-isometries of the spinor form, as they must for a Clifford module",
      all(v == 'skew' for v in adj_signs.values()), str(adj_signs))

print("=== b4: the 4-dim bilinear and the signature of Gamma_4 ===")
bp, bm = sp.symbols('b_plus b_minus', real=True, nonzero=True)
B4 = blk(bp*g_C, bm*g_C)
check("b4 B_4 = diag(b+ Gamma_C, b- Gamma_C) is Cl(2,1)-invariant (every generator skew-adjoint under it) for ANY b+, b-: two scales, one relative sign, NOT fixed by Cl(2,1)",
      all(zM(B4.inv()*g.T*B4 + g) for g in gens.values()))
adj4 = lambda X: sp.simplify(B4.inv()*X.T*B4)
G4dag = adj4(G4)
check("b4' Gamma_4^dag = B_4^{-1} Gamma_4^T B_4 = [[0, -(b-/b+) b Gamma_C],[-(b+/b-) a Gamma_C, 0]]",
      zM(G4dag - off(-(bm/bp)*b*g_C, -(bp/bm)*a*g_C)))
# self-adjoint condition: G4dag = G4  <=>  a = -(bm/bp) b  and  b = -(bp/bm) a  (consistent)  <=>  b = -(bp/bm) a
sa_sol = sp.solve(list(G4dag - G4), [b], dict=True)
check("b4'' Gamma_4 SELF-adjoint under the seat's bilinear  <=>  b = -(b+/b-) a", len(sa_sol) == 1 and zM(sp.Matrix([sa_sol[0][b] + (bp/bm)*a])))
G4_sa = G4.subs(sa_sol[0])
check("b4''' then Gamma_4^2 = (b+/b-) a^2 I_4: THE SIGNATURE OF THE FOURTH DIRECTION IS THE RELATIVE SIGN s = sgn(b+ b-) OF THE SPINOR BILINEAR ACROSS THE TWO SHEETS.  s = +1 -> spacelike, Cl(3,1), 3+1;  s = -1 -> timelike, Cl(2,2)",
      zM(sp.simplify(G4_sa**2 - (bp/bm)*a**2*sp.eye(4))))
sk_sol = sp.solve(list(G4dag + G4), [b], dict=True)
G4_sk = G4.subs(sk_sol[0])
check("b4'''' and Gamma_4 SKEW-adjoint <=> b = +(b+/b-) a, Gamma_4^2 = -(b+/b-) a^2: the skew class gives the OPPOSITE signature for the same s.  Adjoint class and relative sheet-sign together decide; neither alone does",
      len(sk_sol) == 1 and zM(sp.simplify(G4_sk**2 + (bp/bm)*a**2*sp.eye(4))))

print("=== b5: does Gamma_4-invariance of B_4 fix the relative sign? ===")
# the extended Clifford module: vectors of the 4-generator algebra should be (anti-)isometries of B_4 uniformly.
# The three seat generators are skew under B_4.  Require Gamma_4 to be skew as well (uniform Clifford-module convention):
uni = sp.solve(list(G4dag + G4), [b], dict=True)
G4_uni = G4.subs(uni[0])
check("b5 requiring Gamma_4 to be SKEW-adjoint like the other three (uniform Clifford-module convention) gives Gamma_4^2 = -(b+/b-) a^2: spacelike iff s = -1, timelike iff s = +1.  Still hangs on s",
      zM(sp.simplify(G4_uni**2 + (bp/bm)*a**2*sp.eye(4))))
# Gamma_4-invariance of B_4 up to sign: Gamma_4^T B_4 Gamma_4 = lam B_4 ?
lam = sp.Symbol('lambda', real=True)
inv_eqs = list(G4.T*B4*G4 - lam*B4)
inv_sol = sp.solve(inv_eqs, [lam, b], dict=True)
check("b5' Gamma_4^T B_4 Gamma_4 = lambda B_4 is solvable (Gamma_4 is a similitude of B_4) with lambda = -a b (b+/b-)... computed: it constrains b/a to +-(b+/b-) but leaves s = sgn(b+ b-) FREE",
      len(inv_sol) >= 1, str(inv_sol))
both_ok = True
for s_val in (+1, -1):
    B4s = B4.subs({bp: 1, bm: s_val})
    cl_inv = all(zM(B4s.inv()*g.T*B4s + g) for g in gens.values())                 # Cl(2,1)-invariance
    G4s = G4.subs({a: 1, b: -s_val})                                              # the self-adjoint Gamma_4 for this s
    sim = zM(G4s.T*B4s*G4s - (G4s**2)[0, 0]*B4s)                                   # similitude of B_4
    both_ok = both_ok and cl_inv and sim and (G4s**2 == s_val*sp.eye(4))
check("b5'' CONCLUSION (computed for s = +1 AND s = -1): each sign satisfies Cl(2,1)-invariance AND the Gamma_4-similitude condition, and yields Gamma_4^2 = s.  Nothing algebraic fixes s; it is the one datum the readout must supply.  Signature = (adjoint class) x s",
      both_ok)

print("=== b6: the measurement boundary ===")
G4n = G4.subs({a: 1, b: -1})     # spacelike normalisation
evs = G4n.eigenvects()
mixed = all(any(v[0:2, 0] != sp.zeros(2, 1) for v in vecs) and any(v[2:4, 0] != sp.zeros(2, 1) for v in vecs) for _, _, vecs in evs)
check("b6 every eigenvector of Gamma_4 has BOTH block components nonzero: measuring Gamma_4 selects a superposition of the I = +-1 sheets, not a sheet",
      mixed)
check("b6' {I, Gamma_4} = 0: no joint eigenvector; a definite sheet requires an I-measurement after or instead of the Gamma_4 coupling",
      zM(I4*G4n + G4n*I4))

n_ok = sum(CH); n_all = len(CH)
print(f"\nRESULT: {n_ok}/{n_all} checks passed in {time.time()-T0:.1f}s")
print("VERDICT [DERIVED]: the seat's per-block spinor bilinear is forced -- symplectic, equal to Gamma_C, under which every")
print("  generator is skew-adjoint.  On the two sheets it carries two scales and one RELATIVE SIGN s that Cl(2,1) does not")
print("  fix.  Under the induced adjoint, a self-adjoint Gamma_4 has square (b+/b-) a^2: THE SIGNATURE OF THE FOURTH DIRECTION")
print("  IS s.  Coherence forces Gamma_4; the adjoint class of the arrival operation fixes the signature GIVEN s; and s is")
print("  the one datum the readout must supply.  Not chosen for 3+1.")
